### PR TITLE
Option for case-insensitive comparison of input text with trigger

### PR DESCRIPTION
**Pull request by karpov-sv**
Adds an option to do case-insensitive comparison between input text and trigger (was part of #123)

### CODE REVIEW

**Comment by yury-dymov** [comment]
I just double checked with a demo https://yury-dymov.github.io/react-autocomplete-input/ and it's case-insensitive by default. Is the goal to make it case-sensitive?

**Comment by karpov-sv** [comment]
No, it is not case-insensitive by default - the patch is for detection of the trigger, not comparison of contents of autocompletion. So e.g. use `class=` as a trigger and try typing `Class=` - it will not fire by default. The option (disabled by default) allows it to trigger.

**Comment by yury-dymov** [comment]
I see now, can you find a better name for prop, i.e. `triggerCaseInsensitive` or something like and extend the documentation with your example? Will happily merge after that. Sorry for the long delay, just returned from vacation

**Comment by karpov-sv** [comment]
Ok done!

**Pull request merged**
