### PR TITLE
Option to prevent triggering inside the word

### PR DESCRIPTION
**Pull request by karpov-sv**
Originally part of #123.
The feature is disabled by default. To enable, set `triggerInsideWord=false`, then it will not trigger on parts of longer words (e.g. `subclass` will not trigger the options defined for `class`)

### CODE REVIEW

**Comment by yury-dymov** [comment]
This is not needed unless I am missing something. Same can be achieved either with `matchAny` prop or by providing a custom matching regex expression (`[a-zA-Z0-9_\-]+$` most likely)

**Comment by karpov-sv** [comment]
The patch is for trigger detection, not options contents - so `matchAny` and regex both are not applicable here. The problem is when you declare e.g. `class=` as your trigger (to autocomplete the actual value of the class), and then type `subclass=` - it will be triggered by default, which is not a desirable behaviour in some cases.

**Comment by yury-dymov** [comment]
Can we use a `triggerMatchWholeWord` prop name, which aligns well with common language used in IDEs? May I also ask to extend documentation with an example above? This would be sufficient for me to merge this PR

**Comment by karpov-sv** [comment]
Also done!

**Pull request merged**
